package communication;

/**
 *
 * @author Filip
 */
public enum Operation {
    LOGIN,
    LOGOUT,
    KREIRAJ_KLIJENTA,
    NADJI_KLIJENTE,
    UCITAJ_KLIJENTA,
    ZAPAMTI_KLIJENTA,
    OBRISI_KLIJENTA,
    KREIRAJ_AUTOMOBIL,
    NADJI_AUTOMOBILE,
    UCITAJ_AUTOMOBIL,
    ZAPAMTI_AUTOMOBIL,
    OBRISI_AUTOMOBIL,
    KREIRAJ_UVERENJE,
    NADJI_UVERENJA,
    UCITAJ_UVERENJE,
    ZAPAMTI_UVERENJE,
    UCITAJ_LISTU_KLIJENATA,
    KREIRAJ_STAVKU_AUTOMOBILA,
    UCITAJ_LISTU_AUTOMOBILA,
    UCITAJ_LISTU_TIPOVA_AUTOMOBILA,
    UCITAJ_LISTU_SERVISA
}
                                         