/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Filip
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovaniKorisnik = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiDodajAutomobil = new javax.swing.JMenuItem();
        jmiPretraziAutomobil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiDodajKlijenta = new javax.swing.JMenuItem();
        jmiPretraziKlijenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiDodajUverenje = new javax.swing.JMenuItem();
        jmiPretraziUverenje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovaniKorisnik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUlogovaniKorisnik.setText("Ime Korisnika");

        btnLogout.setText("LOGOUT");

        jMenu1.setText("Automobili");

        jmiDodajAutomobil.setText("Dodaj");
        jMenu1.add(jmiDodajAutomobil);

        jmiPretraziAutomobil.setText("Pretraži");
        jMenu1.add(jmiPretraziAutomobil);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Klijenti");

        jmiDodajKlijenta.setText("Dodaj");
        jmiDodajKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajKlijentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiDodajKlijenta);

        jmiPretraziKlijenta.setText("Pretraži");
        jMenu2.add(jmiPretraziKlijenta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Uverenja");

        jmiDodajUverenje.setText("Dodaj");
        jMenu3.add(jmiDodajUverenje);

        jmiPretraziUverenje.setText("Pretraži");
        jMenu3.add(jmiPretraziUverenje);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiDodajKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajKlijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiDodajKlijentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiDodajAutomobil;
    private javax.swing.JMenuItem jmiDodajKlijenta;
    private javax.swing.JMenuItem jmiDodajUverenje;
    private javax.swing.JMenuItem jmiPretraziAutomobil;
    private javax.swing.JMenuItem jmiPretraziKlijenta;
    private javax.swing.JMenuItem jmiPretraziUverenje;
    private javax.swing.JLabel lblUlogovaniKorisnik;
    // End of variables declaration//GEN-END:variables

    public void btnLogoutAddActionListener(ActionListener actionListener){
        btnLogout.addActionListener(actionListener);
    }

    public JLabel getLblUlogovaniKorisnik() {
        return lblUlogovaniKorisnik;
    }
    
    public JButton getBtnLogout() {
        return btnLogout;
    }
    
    public void jmiDodajAutomobilAddActionListener(ActionListener actionListener){
        jmiDodajAutomobil.addActionListener(actionListener);
    }
    
    public void jmiPretraziAutomobilAddActionListener(ActionListener actionListener){
        jmiPretraziAutomobil.addActionListener(actionListener);
    }
    
    public void jmiDodajKlijentaAddActionListener(ActionListener actionListener){
        jmiDodajKlijenta.addActionListener(actionListener);
    }
    
    public void jmiPretraziKlijentaAddActionListener(ActionListener actionListener){
        jmiPretraziKlijenta.addActionListener(actionListener);
    }
    
    public void jmiDodajUverenjeAddActionListener(ActionListener actionListener){
        jmiDodajUverenje.addActionListener(actionListener);
    }
    
    public void jmiPretraziUverenjeAddActionListener(ActionListener actionListener){
        jmiPretraziUverenje.addActionListener(actionListener);
    }
}
